---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo
  labels:
    name: todo
spec:
  replicas: ${TPL_REPLICAS:-3}
  template:
    metadata:
      labels:
        name: todo
    spec:
      containers:
      - name: todo
        image: gcr.io/modular-terra-131010/todo-service:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        args: ["start"]
        ports:
        - name: http-server
          containerPort: 5000 
          protocol: TCP
